# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SSFarmShop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'IGListKit'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'Kingfisher'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Then'
  pod 'SwiftDate'

  # Pods for SSFarmShop

  target 'SSFarmShopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SSFarmShopUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
